#!/usr/bin/env bash

set -Eeuxo pipefail

IFS=$'\n\t'

trap 'echo Error at about $LINENO' ERR


sudo pacman -S --noconfirm xmonad xmonad-contrib xmobar stalonetray dmenu scrot cabal-install xcompmgr
sudo cabal update
sudo cabal install --global yeganesh

git clone https://github.com/jeremyottley/xmo.git .xmonad
#ln -s ~/.xmonad/bin/xsession ~/.xsession

git clone https://github.com/jeremyottley/st.git
cd st
make
sudo make install
cd ~

git clone https://github.com/jeremyottley/.fonts.git
sudo fc-cache -fv
