#!/bin/sh
# Script to configure X, start common apps, and start xmonad.


# Configure PATH so that we can access our scripts below
PATH=$PATH:~/.cabal/bin:~/.xmonad/bin

# Configure X
xsetroot -cursor_name left_ptr &
xrdb -merge ~/.Xresources &
setxkbmap -option "ctrl:nocaps" &

# Start a window compositor. This ensures Google Chrome paints correctly.
xcompmgr -n &

# Start the system tray
stalonetray &

# Wallpaper
feh --randomize --bg-fill ~/.wallpapers/*

# Start screensaver
gnome-screensaver &

# Start sound server
pulseaudio --start --log-target=syslog &

gnome-session &
